# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d1407a90bec1cb1ff0c9a90766677acc15ded722e6d1f85fd20429c3f2f7ac06a0e66668df59e1dfd3a337e6653dd31a3ef05730adb7a889b753e4f18d59303

test:
  secret_key_base: b502a668a85f27d82485b29a94d185b6d7604e29c0211ffd5230d2c9f574c7e4333ec866168a5e3486720d5a3f8679db9b2c3cbfce24092fa76377fdd981ab8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
